### ISSUE TITLE
appendOldTweet hook takes too much memory

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#167]
The 'appendOldTweet' hook used to gather data for the tweet info output file seems to cause bad malloc errors when running simulations with a large number of retweets. I've presently commented this out from the TweetBank.cpp file and pushed this change. This will allow simulations with plenty of retweets to be run, but will not allow the tweet info output file to gather information. How this will be handled going forward is I guess up for discussion, but I just wanted everyone to be aware of this.

**Comment by ludamad** [comment]
What sort of errors? Is the process running out of memory?

**Comment by nbuhagiar** [comment]
This is the error I get

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

when running with a network with a high tweet rate that allows retweeting.

**Comment by ludamad** [comment]
Ah, that's what I thought, but not quite the same implication as 'bad malloc' as this comes from C++-style allocation, not malloc :) Yes this is simply because keeping all of the tweets takes up too much memory. This isn't really an error per se. In my fork of the repo I have this guarded based on whether tweet summary information is requested. Otherwise, a different output scheme can be implemented.

**Comment by nbuhagiar** [comment]
That was my fault, I misread the error message when I first posted this.
Sorry for the confusion. Just thought this worth mentioning so that
everyone was aware of it.

**Comment by jig08** [comment]
@nbuhagiar Seems to be resolved, closing this issue.
