### ISSUE TITLE
'summary_output_rate' Consistency

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#25]
Though the 'stdout_summary' is outputted to the screen and updated at a rate influenced by the 'summary_output_rate', this update rate becomes much slower when simulating a more complex network. Is there anyway to keep this update rate roughly the same for every simulation? The complex networks found in the 'benchmarks' directory have a 'summary_output_rate' of 1 but take a very long time for their 'stdout_summary' to be updated

**Comment by nbuhagiar** [comment]
A 'summary_output_rate' that has an option of being updated at a real time rate or at a rate in terms of the number of steps in the KMC loop may be ideal, as well as an output of the number of steps in the KMC loop to the display

**Comment by nbuhagiar** [comment]
Just wondering what we thought of the idea of having the stdout_summary also being updated every simulated minute to the screen and in the 'DATA_vs_TIME' file.

**Comment by itamblyn** [comment]
Do you mean real minute (i.e. so it updates the screen every 60 seconds?)

- Isaac

**Comment by nbuhagiar** [comment]
I meant simulated minute, but we could implement an option to have it update in simulated time or real time if you'd like

**Comment by kryczko** [comment]
Hey Nick,

A simulated minute will most likely be way too much output. You have to remember that every time you do input/output, you are slowing down the program. Instead of using clock cycles on the core algorithm you would be using them to write to disk too frequently in this case. 

The only time this could be useful is for very large graphs where a simulated minute could take several real minute. 

I think adding an option to print every x REAL minutes would be useful. Perhaps you can close this Nick and open an enhancement issue about adding this feature in.

Kevin

**Comment by nbuhagiar** [comment]
Done. Thanks Kevin!
