### ISSUE TITLE
Less Follows Occurring in a 'twitter_suggest' Follow Model than Expected

### ISSUE THREAD

**Issue by nbuhagiar** [hashkat/hashkat#75]
Running the same network simulation first using a 'random' follow model and then again using a 'twitter_suggest' follow model, vastly less follows occurred than expected in the 'twitter_suggest' follow model simulation. The 'main_stats.dat' file for each simulation is shown below.

'random':

![random_follows](https://cloud.githubusercontent.com/assets/10453145/10615616/df0f9440-772e-11e5-9aaa-974ac68fd067.png)

'twitter_suggest':

![preferential_follows](https://cloud.githubusercontent.com/assets/10453145/10615620/e194cc76-772e-11e5-8c5d-4fdfd848e243.png)

Do you have any idea why this could be the case? Copies of these input files can be found in the 'hashkat' directory under 'bugs/075'

**Comment by kryczko** [comment]
I have found and fixed the bug, pull to get latest version. The stat being recorded was in an if statement that wasn’t being satisfied due to the small network size and using the preferential attachment model. It turns out, that the stat being recorded didn’t need to be in the for loop (for some reason I thought it needed to before, which is why it was there). You will still get like 800-900 follows, but the follow attempts have gone up to match the random method.
